export const ACTIONS = {
  INITIALIZE_GRID: 'INITIAILIZE_GRID',
  GENERATE_RANDOM_GRID: 'GENERATE_RANDOM_GRID',
  ADVANCE_GENERATION: 'ADVANCE_GENERATION',
  TOGGLE_LIFE: 'TOGGLE_LIFE',
  CHANGE_IS_TICKING: 'CHANGE_IS_TICKING',
  RESET_GRID: 'RESET_GRID',
}

export const TEXT = {
  BTN: {
    START: 'Start',
    STOP: 'Stop',
  }
}
